CREATE TABLE campos_agro (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100),
    area_ha NUMBER,
    produtividade_estimada NUMBER,
    data_colheita DATE,
    maquinas_alocadas VARCHAR2(500),
    custo_fixo NUMBER
);
